[package]

name = "capnp-rpc"
version = "0.10.0"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>" ]
build = "build.rs"
license = "MIT"
description = "implementation of the Cap'n Proto remote procedure call protocol"
repository = "https://github.com/dwrensha/capnproto-rust"
documentation = "http://docs.capnproto-rust.org/capnp_rpc/"
categories = ["network-programming"]
autoexamples = false
edition = "2018"

readme = "README.md"

[lib]

name = "capnp_rpc"
path = "src/lib.rs"

[build-dependencies]
capnpc = { version = "0.10", path = "../capnpc" }

[dependencies]
futures-preview = "0.3.0-alpha.18"
capnp-futures = { version = "0.10.1", path = "../capnp-futures" }
capnp = {version = "0.10", path = "../capnp"}
