[package]
name = "capnp-http-requests"
version = "0.1.0"
authors = ["David Renshaw <david@sandstorm.io>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "http-requests"
path = "src/main.rs"

[build-dependencies]
capnpc = { path = "../../../capnpc" }

[dependencies]
capnp = { path = "../../../capnp" }
futures-preview = "0.3.0-alpha.18"
hyper = { git = "https://github.com/hyperium/hyper" }
tokio = "0.2.0-alpha.4"
tokio-executor = "0.2.0-alpha.4"
futures-tokio-compat = { git = "https://github.com/Nemo157/futures-tokio-compat" }

[dependencies.capnp-rpc]
path = "../.."
